name: Run `npm ci` and `npm run build` with latest Node versions and C++ compilers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        cxx: [g++-9, g++-10, g++-11, g++-12, g++-13]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up C++ compiler (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cxx }}
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm ci
          npm run build
